### ISSUE TITLE
how the hell !?

### ISSUE THREAD

**Issue by tizu69** [Mist3rBru/go-clack#1]
was this manually built? or is there some tool that recreated the packages in go? I'm kinda surprised this is as close to the original code as it is :thinking:

**Comment by Mist3rBru** [comment]
Hey @tizu69, thanks for noticing the resemblance and for your question!

I manually rebuilt the package in Go from scratch. Having contributed to the original `clack` package, I was already familiar with its architecture and core logic. 

My goal was to ensure it stayed true to the original, while optimizing it for use in Go-specific projects. 

If you have any suggestions or feedback on the Go implementation, I’d love to hear them!
