### ISSUE TITLE
Add `LICENSE` file

### ISSUE THREAD

**Issue by Neved4** [Mist3rBru/go-clack#3]
Thx for this amazing project! 💙

Adding a license would help show `go-clack`'s docs on https://pkg.go.dev/

Currently you get something like:

![](https://github.com/user-attachments/assets/8937f20c-8bb0-4eb1-a436-30f49c030e6c)

**Comment by Mist3rBru** [comment]
Hey @Neved4, thanks for the issue!

I just added a License on #4, now you can see the package's documentation on https://pkg.go.dev/github.com/Mist3rBru/go-clack@v0.1.15

**Comment by Neved4** [comment]
It's showing rn, thx for being awesome! @Mist3rBru
